### ISSUE TITLE
Not seeing this published in jcenter

### ISSUE THREAD

**Issue by adamkeyser** [nebula-plugins/nebula-hollow-plugin#2]
Could not resolve all dependencies for configuration ':classpath'.
   > Could not find com.netflix.nebula:nebula-hollow-plugin:.
     Searched in the following locations:
         https://jcenter.bintray.com/com/netflix/nebula/nebula-hollow-plugin//nebula-hollow-plugin-.pom
         https://jcenter.bintray.com/com/netflix/nebula/nebula-hollow-plugin//nebula-hollow-plugin-.jar
     Required by:
         project :

**Comment by IgorPerikov** [comment]
Hi! As far as I know, It is not suppose to be there for now. All netflixoss stuff must pass through some inner publications. After that some inner system will publish it to jcenter. Further comments are up to the Netflix guys, I guess.

**Comment by IgorPerikov** [comment]
@dkoszewnik hi Drew, do you know anything about further development/publication?

**Comment by ghost** [comment]
@IgorPerikov @adamkeyser I'm working on this now. There's some one-time setup that I became a blocker on; apologies for the delay. I'll follow up when it's published.

**Comment by ghost** [comment]
🔜 

If all is well, `v0.1.0-rc.1` will be published soon. Went with a pre-release; according to @rspieldenner we may need to make some tweaks yet. Once that's all good, I'll release `v0.1.0`.

**Comment by ghost** [comment]
Published as `v0.2.1`

https://jcenter.bintray.com/com/netflix/nebula/nebula-hollow-plugin/0.2.0/

*It's been synced to maven central, but isn't showing up in search yet.*

Going forward releases made with tags that follow [semver](http://semver.org/) will automatically trigger artifact publishes.

Thanks again for the plugin, @IgorPerikov. Thanks for the release pipeline help, @rspieldenner.
