### ISSUE TITLE
classPostfix configuration not working

### ISSUE THREAD

**Issue by vgrigoriu** [nebula-plugins/nebula-hollow-plugin#22]
When I set `classPostfix` to `Hollow`, the generated code refers to a `StringHollow` class (presumably the same thing as `HString`) but there's no `StringHollow` class in the code generated. I'm pretty sure I'm using version 1.1.7 of the plugin.

 I tried calling `HollowAPIGenerator` directly, and things seem to work as expected (there's a `StringHollow` class generated).

Let me know if you need a repro or other details.

**Comment by vgrigoriu** [comment]
I discovered that this is fixed by upgrading `hollowVersion` [here](https://github.com/nebula-plugins/nebula-hollow-plugin/blob/cfe4dc1ca16b517d0f7d4119567aa7ec96ca9c9c/gradle/dependencies.gradle#L21). I can provide a PR but I'm not sure how a new version of the plugin is published?

**Comment by rpalcolea** [comment]
Hi! thanks for looking into this

I upgraded to latest hollow and released v2.0.0. Should be out in a bit https://travis-ci.org/nebula-plugins/nebula-hollow-plugin/builds/660870112

**Comment by vgrigoriu** [comment]
Thanks!
